"""Write docs/evaluation/model-results.md from the generated metrics.

Run after `python -m ml.scripts.evaluate_all`. Every number in the report is
read from ml/reports/metrics/model_metrics.json; nothing is typed in by hand.

Usage (from the repository root):
    python -m ml.scripts.generate_report
"""

from __future__ import annotations

import sys

from ml.src.evaluation.reports import read_json
from ml.src.paths import DOCS_DIR, METRICS_DIR, REPO_ROOT

RESULTS_MD = DOCS_DIR / "evaluation" / "model-results.md"
README_MD = REPO_ROOT / "README.md"
# Documents that carry a generated results block between the two markers below.
DOCUMENTS_WITH_RESULTS = (
    README_MD,
    DOCS_DIR / "presentation" / "project-summary.md",
    DOCS_DIR / "presentation" / "pitch.md",
)
README_START = "<!-- results:start (generated by ml/scripts/generate_report.py; do not edit) -->"
README_END = "<!-- results:end -->"
_METRICS = ("accuracy", "precision", "recall", "f1", "roc_auc", "brier")
_TITLES = {"accuracy": "Accuracy", "precision": "Precision", "recall": "Recall", "f1": "F1",
           "roc_auc": "ROC-AUC", "brier": "Brier"}


def _cv_cell(summary, metric):
    return f"{summary[metric]['mean']:.3f} ± {summary[metric]['std']:.3f}"


def _holdout_cell(holdout, metric):
    interval = holdout["confidence_intervals_95"][metric]
    return f"{holdout['metrics'][metric]:.3f} ({interval['lower']:.3f}–{interval['upper']:.3f})"


def render(metrics: dict, classes: dict) -> str:
    first = next(iter(metrics.values()))
    training, cv = first["training"], first["training"]["cross_validation"]
    lines = [
        "# Model results",
        "",
        "> Generated by `python -m ml.scripts.generate_report` from `ml/reports/metrics/model_metrics.json`.",
        "> Do not edit by hand; rerun the pipeline instead.",
        "",
        "These are results of a research/educational prototype on one small public dataset. They are",
        "not evidence of clinical performance, and the models have not been externally validated.",
        "",
        "## Data and validation",
        "",
        f"- {training['n_development'] + training['n_holdout']} records: {training['n_development']} "
        f"development, {training['n_holdout']} holdout (one patient-level split shared by all four models).",
        f"- Model selection: repeated stratified {cv['n_splits']}-fold cross-validation, {cv['n_repeats']} "
        "repeats, on the development set only, with preprocessing fitted inside each fold.",
        "- The holdout set was evaluated once, after algorithm, calibration and threshold were fixed.",
        "- `LAD`, `LCX`, `RCA` and `Cath` are never model inputs.",
        "",
        "## Class distribution (full dataset)",
        "",
        "| Target | Positive | Negative | Positive rate |",
        "|---|---|---|---|",
    ]
    for target, info in classes.items():
        lines.append(f"| {target} | {info['n_positive']} | {info['n_negative']} | {info['positive_rate'] * 100:.1f}% |")

    lines += ["", "## Selected models", "", "| Target | Model | Calibration | Decision threshold |", "|---|---|---|---|"]
    for target, m in metrics.items():
        lines.append(f"| {target} | `{m['candidate']}` | {m['calibration']['method']} | {m['decision_threshold']:.3f} |")

    lines += [
        "",
        "## Cross-validation (development set)",
        "",
        "Mean ± standard deviation across folds for the final configuration (selected model with its",
        "adopted calibration and threshold, both fitted inside each training fold).",
        "",
        "| Target | " + " | ".join(_TITLES[m] for m in _METRICS) + " |",
        "|---|" + "---|" * len(_METRICS),
    ]
    for target, m in metrics.items():
        lines.append(f"| {target} | " + " | ".join(_cv_cell(m["nested_cross_validation"], k) for k in _METRICS) + " |")

    lines += [
        "",
        "## Holdout set",
        "",
        f"Point estimate with a 95% bootstrap interval ({first['holdout']['bootstrap_resamples']} resamples). "
        f"With {training['n_holdout']} records the intervals are wide; read them, not just the point estimates.",
        "",
        "| Target | n | " + " | ".join(_TITLES[m] for m in _METRICS) + " |",
        "|---|---|" + "---|" * len(_METRICS),
    ]
    for target, m in metrics.items():
        lines.append(f"| {target} | {m['holdout']['n']} | " + " | ".join(_holdout_cell(m["holdout"], k) for k in _METRICS) + " |")

    lines += [
        "",
        "### Reference: a model with no patient information",
        "",
        "Predicting the development-set positive rate for every patient gives the scores below. A model",
        "is only useful to the extent it beats them.",
        "",
        "| Target | Accuracy | Brier | ROC-AUC |",
        "|---|---|---|---|",
    ]
    for target, m in metrics.items():
        b = m["holdout"]["reference_baseline"]
        lines.append(f"| {target} | {b['accuracy']:.3f} | {b['brier']:.3f} | {b['roc_auc']:.3f} |")

    lines += ["", "### Confusion matrices (holdout)", "", "| Target | True negative | False positive | False negative | True positive |", "|---|---|---|---|---|"]
    for target, m in metrics.items():
        cm = m["holdout"]["metrics"]["confusion_matrix"]
        lines.append(f"| {target} | {cm['tn']} | {cm['fp']} | {cm['fn']} | {cm['tp']} |")

    lines += ["", "## Decisions", ""]
    for target, m in metrics.items():
        lines += [
            f"### {target}",
            "",
            f"- **Selection:** {m['selection_reason']}",
            f"- **Calibration:** {m['calibration']['reason']}",
            f"- **Threshold:** {m['calibration']['threshold_reason']}",
            "- **Most influential features (mean |SHAP| on the development set):** "
            + ", ".join(f["label"] for f in m["global_importance"]["features"][:8])
            + ". These describe what the model relies on; they are not causal findings.",
            "",
        ]

    lines += [
        "## Figures",
        "",
        "Generated under `ml/reports/figures/`: `roc_curves.png`, `confusion_matrices.png`,",
        "`calibration_curves.png`, `class_distribution.png`, `model_comparison.png` and",
        "`shap_global_<target>.png`. The full candidate comparison is in",
        "`ml/reports/model_comparison/model_comparison.md`.",
        "",
    ]
    return "\n".join(lines)


def render_readme_table(metrics: dict) -> str:
    """Compact holdout table for the README, from the same metrics file."""
    first = next(iter(metrics.values()))
    lines = [
        README_START,
        "",
        f"Holdout set ({first['training']['n_holdout']} records, evaluated once). Brackets are 95% bootstrap intervals.",
        "",
        "| Target | Model | Accuracy | Precision | Recall | F1 | ROC-AUC | No-information accuracy |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for target, m in metrics.items():
        holdout = m["holdout"]
        values = holdout["metrics"]
        auc = holdout["confidence_intervals_95"]["roc_auc"]
        lines.append(
            f"| {target} | {m['algorithm'].replace('_', ' ')} | {values['accuracy']:.3f} | {values['precision']:.3f} "
            f"| {values['recall']:.3f} | {values['f1']:.3f} | {values['roc_auc']:.3f} ({auc['lower']:.2f}–{auc['upper']:.2f}) "
            f"| {holdout['reference_baseline']['accuracy']:.3f} |"
        )
    lines += ["", README_END]
    return "\n".join(lines)


def update_document(path, metrics: dict) -> bool:
    """Replace the generated results block in one document, if it exists and has the markers."""
    if not path.is_file():
        return False
    text = path.read_text(encoding="utf-8")
    if README_START not in text or README_END not in text:
        return False
    before, rest = text.split(README_START, 1)
    after = rest.split(README_END, 1)[1]
    path.write_text(before + render_readme_table(metrics) + after, encoding="utf-8")
    return True


def main() -> int:
    metrics_path = METRICS_DIR / "model_metrics.json"
    if not metrics_path.is_file():
        print("No metrics found. Run `python -m ml.scripts.train_all` and "
              "`python -m ml.scripts.evaluate_all` first.", file=sys.stderr)
        return 2
    metrics = read_json(metrics_path)
    RESULTS_MD.parent.mkdir(parents=True, exist_ok=True)
    RESULTS_MD.write_text(
        render(metrics, read_json(METRICS_DIR / "class_distribution.json")), encoding="utf-8"
    )
    print(f"wrote {RESULTS_MD.relative_to(REPO_ROOT).as_posix()}")
    for document in DOCUMENTS_WITH_RESULTS:
        if update_document(document, metrics):
            print(f"updated the results table in {document.relative_to(REPO_ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
